src/pocketmine/Server.php, src/pocketmine/level/generator/biome/Biome.php, src/pocketmine/level/generator/normal/Normal2.php
Reverts TesseractTeam/Tesseract#89
Need to be tested, fully.
=> Revert "Biome generator"

src/pocketmine/lang/locale/chs.ini, src/pocketmine/lang/locale/deu.ini, src/pocketmine/lang/locale/jpn.ini
These need to at least be updated if they need to be gone or not xD
=> Removed /cave, /biome, and /lvdat nodes

ci.sh
=> fixed ci.sh

src/pocketmine/Player.php, src/pocketmine/Server.php, src/pocketmine/block/FlowerPot.php, src/pocketmine/entity/Entity.php, src/pocketmine/inventory/BaseInventory.php, src/pocketmine/level/generator/normal/Normal.php, src/pocketmine/tile/Sign.php
=> Git merge branch "master" into "Action-bar"

src/pocketmine/Player.php, src/pocketmine/tile/Sign.php
=> Git merge "master" into "Transfer-Event"

src/pocketmine/Player.php, src/pocketmine/tile/Sign.php
=> Git merge "master" with "1.0.4"

src/pocketmine/Server.php
Someone tried to implement pmmp/PocketMine-MP#195 but failed. They did not fully implement it. Only partly, and that totally messed it up ;P
...
=> Really?! WHY?!?!?!?!?!

src/pocketmine/Player.php, src/pocketmine/Server.php, src/pocketmine/event/player/PlayerTextPreSendEvent.php
=> Fix player data saving blame @remotevase

src/pocketmine/Player.php, src/pocketmine/network/protocol/Info.php, src/pocketmine/network/protocol/LoginPacket.php
Accepts multiple version of MCPE... 
...
=> Protocol hack

src/pocketmine/command/defaults/BanCommand.php, src/pocketmine/permission/BanList.php
This PR only applies to /ban. /banip and Genisys ban commands are not affected by this PR. 
...
=> Ban handled by ban function and not /ban

src/pocketmine/command/defaults/TransferCommand.php
=> Fix Perm and Others (TransferCommand)

src/pocketmine/Player.php, src/pocketmine/Server.php, src/pocketmine/block/Rail.php, src/pocketmine/block/RedstoneTorch.php, src/pocketmine/block/TripwireHook.php, src/pocketmine/block/WoodenButton.php, src/pocketmine/command/defaults/BanCommand.php, src/pocketmine/entity/EnderDragon.php, src/pocketmine/entity/EnderPearl.php, src/pocketmine/entity/Entity.php, src/pocketmine/level/generator/normal/Normal.php, src/pocketmine/network/RakLibInterface.php, src/pocketmine/resources/tesseract_chs.yml, src/pocketmine/resources/tesseract_eng.yml, src/pocketmine/resources/tesseract_fin.yml, src/pocketmine/resources/tesseract_jpn.yml, src/pocketmine/resources/tesseract_kor.yml, src/pocketmine/resources/tesseract_vie.yml, src/pocketmine/resources/tesseract_zho.yml
=> Update Enchantment Rewrite Branch

src/pocketmine/resources/creativeitems.json
=> Update creativeitems.json for wet sponge

src/pocketmine/Player.php, src/pocketmine/inventory/AnvilInventory.php, src/pocketmine/inventory/BaseInventory.php, src/pocketmine/inventory/BaseTransaction.php, src/pocketmine/item/Item.php
=> PMMP PORT: Remove deepequals and change it to equals

src/pocketmine/item/Item.php
=> Fixed transaction bug?

src/pocketmine/Player.php
This add fixes the bugs I had quoted in an issue ! Tested and approved ! (I had to compare Nukkit to Tesseract and I finally found the error).
=> Fix titles bugs

src/pocketmine/Player.php
=> Fixes titles bug

src/pocketmine/resources/tesseract_chs.yml
=> Updated tesseract_chs.yml

src/pocketmine/Player.php
Just add it to inventory instead of drop !
Tested on my server, and still use it, I was afraid that it will allow toolbox items cheats, but nope :D .
Please test it before merging, even if I tested it.
...
=> why items should drop?

src/pocketmine/network/protocol/Info.php
=> Fix Linux's Stupid Error

src/pocketmine/item/Item.php
=> Noobies Here

src/pocketmine/Player.php
=> Working bows

src/pocketmine/Server.php, src/pocketmine/inventory/InventoryType.php, src/pocketmine/level/generator/object/AcaciaTree.php, src/pocketmine/level/generator/object/BigTree.php, src/pocketmine/level/generator/object/BirchTree.php, src/pocketmine/level/generator/object/DarkOakTree.php, src/pocketmine/level/generator/object/JungleTree.php, src/pocketmine/level/generator/object/NetherOre.php, src/pocketmine/level/generator/object/NetherOreTop.php, src/pocketmine/level/generator/object/OakTree.php, src/pocketmine/level/generator/object/Ore.php, src/pocketmine/level/generator/object/OreType.php, src/pocketmine/level/generator/object/Pond.php, src/pocketmine/level/generator/object/SpruceTree.php, src/pocketmine/level/generator/object/TallGrass.php, src/pocketmine/level/generator/object/Tree.php
=> add some objects

src/pocketmine/PocketMine.php
Reverts TesseractTeam/Tesseract#1078
=> Revert "Immature."

README.md
=> Its Android not ODROID. LOL XD

src/pocketmine/block/DragonEgg.php
...
Works.Now dragon egg can fall if you place it somewhere high.
=> A bit more functionable draggon egg from clearsky

src/pocketmine/network/protocol/BatchPacket.php
=> Fix BatchPacket
